# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

domains:
  operations:
    # Domain operations
    - update: update_permission
    - read: read_permission
    - enable: enable_permission
    - disable: disable_permission
    - list: read_permission
    - send_invitation: manage_role_permission
    - list_domain_invitation: manage_role_permission
    - delete_invitation: manage_role_permission
    # LLM operations
    - llm_create: llm_create_permission
    - llm_update: llm_update_permission
    - llm_read: llm_read_permission
    - llm_delete: llm_delete_permission
    - llm_chat_completions: llm_chat_completions_permission
    - llm_completions: llm_completions_permission
    - llm_embeddings: llm_embeddings_permission
    - llm_transcription: llm_transcription_permission
    - llm_translation: llm_translation_permission
    - llm_utility: llm_utility_permission
    - llm_pooling: llm_pooling_permission
    - llm_classification: llm_classification_permission
    - llm_scoring: llm_scoring_permission
    - llm_rerank: llm_rerank_permission
    # Audit log operations
    - audit_log_read: audit_log_read_permission
    - audit_log_export: audit_log_export_permission

  roles_operations:
    # Domain roles operations
    - add: manage_role_permission
    - remove: manage_role_permission
    - update: manage_role_permission
    - retrieve: view_role_users_permission
    - retrieve_all: view_role_users_permission
    - add_actions: manage_role_permission
    - list_actions: view_role_users_permission
    - check_actions_exists: view_role_users_permission
    - remove_actions: manage_role_permission
    - remove_all_actions: manage_role_permission
    - add_members: add_role_users_permission
    - list_members: view_role_users_permission
    - check_members_exists: view_role_users_permission
    - remove_members: remove_role_users_permission
    - remove_all_members: remove_role_users_permission
