# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

domains:
  operations:
    - create: create_permission
    - update: update_permission
    - read: read_permission
    - enable: enable_permission
    - disable: disable_permission
    - delete: delete_permission
    - list: read_permission
    - send_invitation: manage_role_permission
    - list_invitation: membership_permission
    - list_domain_invitation: manage_role_permission
    - delete_invitation: manage_role_permission
  llm_operations:
    - create: llm_create_permission
    - update: llm_update_permission
    - read: llm_read_permission
    - delete: llm_delete_permission
    - chat_completions: llm_chat_completions_permission
    - completions: llm_completions_permission
    - embeddings: llm_embeddings_permission
    - transcription: llm_transcription_permission
    - translation: llm_translation_permission
    - utility: llm_utility_permission
    - pooling: llm_pooling_permission
    - classification: llm_classification_permission
    - scoring: llm_scoring_permission
    - rerank: llm_rerank_permission
  audit_log_operations:
    - read: audit_log_read_permission
    - export: audit_log_export_permission
  roles_operations:
    - add: manage_role_permission
    - remove: manage_role_permission
    - update: manage_role_permission
    - retrieve: view_role_users_permission
    - retrieve_all: view_role_users_permission
    - add_actions: manage_role_permission
    - list_actions: view_role_users_permission
    - check_actions_exists: view_role_users_permission
    - remove_actions: manage_role_permission
    - remove_all_actions: manage_role_permission
    - add_members: add_role_users_permission
    - list_members: view_role_users_permission
    - check_members_exists: view_role_users_permission
    - remove_members: remove_role_users_permission
    - remove_all_members: remove_role_users_permission
  llm_roles_operations:
    - add: llm_manage_role_permission
    - remove: llm_manage_role_permission
    - update: llm_manage_role_permission
    - retrieve: llm_view_role_users_permission
    - retrieve_all: llm_view_role_users_permission
    - add_actions: llm_manage_role_permission
    - list_actions: llm_view_role_users_permission
    - check_actions_exists: llm_view_role_users_permission
    - remove_actions: llm_manage_role_permission
    - remove_all_actions: llm_manage_role_permission
    - add_members: llm_add_role_users_permission
    - list_members: llm_view_role_users_permission
    - check_members_exists: llm_view_role_users_permission
    - remove_members: llm_remove_role_users_permission
    - remove_all_members: llm_remove_role_users_permission
  audit_log_roles_operations:
    - add: audit_log_manage_role_permission
    - remove: audit_log_manage_role_permission
    - update: audit_log_manage_role_permission
    - retrieve: audit_log_view_role_users_permission
    - retrieve_all: audit_log_view_role_users_permission
    - add_actions: audit_log_manage_role_permission
    - list_actions: audit_log_view_role_users_permission
    - check_actions_exists: audit_log_view_role_users_permission
    - remove_actions: audit_log_manage_role_permission
    - remove_all_actions: audit_log_manage_role_permission
    - add_members: audit_log_add_role_users_permission
    - list_members: audit_log_view_role_users_permission
    - check_members_exists: audit_log_view_role_users_permission
    - remove_members: audit_log_remove_role_users_permission
    - remove_all_members: audit_log_remove_role_users_permission
